### ISSUE TITLE
`govendor sync` doesn't

### ISSUE THREAD

**Issue by djmitche** [taskcluster/taskcluster-worker#189]
```
dustin@lamport ~/go/src/github.com/taskcluster/taskcluster-worker [master] $ govendor sync
# cd /home/dustin/go/.cache/govendor/github.com/taskcluster/go-got; git reset --hard d44fc82164dd1687157b9730d65b8fb1d59415af
fatal: Could not parse object 'd44fc82164dd1687157b9730d65b8fb1d59415af'.
# cd /home/dustin/go/.cache/govendor/github.com/taskcluster/taskcluster-client-go; git reset --hard 72514fa85efd9d7e22af0d61a6aa5bed471a95d9
fatal: Could not parse object '72514fa85efd9d7e22af0d61a6aa5bed471a95d9'.
```
Shouldn't it run `git fetch` in those repos?

Deleting the cache and re-running seems to let govendor complete successfully.

**Comment by djmitche** [comment]
Note that this was an update -- I had run `govendor sync` last week while working on the project, and pulled an updated master today.  I got dependency errors, so I re-ran `govendor sync` and the above is what I got.  @jonasfj says it still works in a clean environment.

**Comment by petemoore** [comment]
@djmitche 

Sounds like a govendor bug.

Maybe it silently fetches from the wrong remote? What do you get from:

1) Running `govendor sync -v` ?
2) `cd /home/dustin/go/.cache/govendor/github.com/taskcluster/go-got; git remote -v`

**Comment by djmitche** [comment]
I blew away the cache directory on Jonas's advice.  Now I can't reproduce this.  I tried deleting `$GOPATH/.cache/govendor` and `vendor/*/`, checking out an old version (5605420), `govendor sync`, then going back to master, but that doesn't reproduce the issue.  There must be a cache somewhere else, too?  That, or maybe at one point I had something checked out before one of the "fix govendor" commits, and that un-fixed state poisoned the cache?

**Comment by djmitche** [comment]
Welp, it happened again:
```
dustin@lamport ~/go/src/github.com/taskcluster/taskcluster-worker [bug1342257] $ govendor sync -v
fetch "github.com/taskcluster/go-schematypes"
# cd /home/dustin/go/.cache/govendor/github.com/taskcluster/go-schematypes; git reset --hard a1195e860f14952214e9f5269459601e3266475b
fatal: Could not parse object 'a1195e860f14952214e9f5269459601e3266475b'.
```

```
$ git -C /home/dustin/go/.cache/govendor/github.com/taskcluster/go-schematypes remote -v
origin  https://github.com/taskcluster/go-schematypes (fetch)
origin  git@github.com:taskcluster/go-schematypes (push)
```
and
```
$ git -C /home/dustin/go/.cache/govendor/github.com/taskcluster/go-schematypes log -1
commit a1195e860f14952214e9f5269459601e3266475b
Author: Jonas Finnemann Jensen <jopsen@gmail.com>
Date:   Fri Mar 3 13:59:25 2017 -0800

    Added a few utility functions
```
and
```
$ govendor sync -v
$
```
(no output)

But now `go build` seems to work -- presumably the `git pull` on `go-schematypes` was enough, and just barfed that way?

**Comment by walac** [comment]
I just had the same issue.

**Comment by petemoore** [comment]
Now I had it too!

```
pmoore@Petes-iMac:~/go/src/github.com/taskcluster/taskcluster-worker new-tests $ govendor sync
# cd /Users/pmoore/go/.cache/govendor/github.com/taskcluster/go-schematypes; git reset --hard a1195e860f14952214e9f5269459601e3266475b
fatal: Could not parse object 'a1195e860f14952214e9f5269459601e3266475b'.
pmoore@Petes-iMac:~/go/src/github.com/taskcluster/taskcluster-worker new-tests $ govendor sync
pmoore@Petes-iMac:~/go/src/github.com/taskcluster/taskcluster-worker new-tests $ 
```

**Comment by petemoore** [comment]
Note, govendor has [**71** open issues](https://github.com/kardianos/govendor/issues) currently

**Comment by petemoore** [comment]
.... so it looks like the workaround is just to run `govendor sync` twice ....

**Comment by djmitche** [comment]
OK, that's a decent workaround :)
