### ISSUE TITLE
Task Logs do not include headers/footers similar to other workers

### ISSUE THREAD

**Issue by gregarndt** [taskcluster/taskcluster-worker#262]
Other worker implementations include a set of information in the task log when the task starts, as well as some completion information at the end.  The workers are not consistent with what they include, but the information is generally helpful to have.

**Comment by jonasfj** [comment]
@gregarndt what do you suggest we include... I think it would be easy to write a plugin that writes some metadata to the task log... It could race with other log messages that are written immediately, but I don't think there is any... Unless fetching an image fails or something like that...

Note. We could also make a config option for the livelog plugin... but that would work less nice if in some future we add additional logging plugins...

**Comment by jonasfj** [comment]
Please outline a bullet point list of what you want and I'll write up a plugin..

**Comment by gregarndt** [comment]
I'm going to defer to @petemoore on the actual details, really we should be trying to come up with a consistent way of logging these headers and footers going forward.  right now generic-worker and docker-worker output different things in different formats.  This is a time to think about what we want in it, and write it up.

I know having information about worker version, instance type, ip address, and some other metadata is useful in the header.

In the footer having how long the task took, the status code, artifacts uploaded, etc.

**Comment by jonasfj** [comment]
Log prefixes landed in https://github.com/taskcluster/taskcluster-worker/pull/268

I suspect we'll expand with more key-value pairs as we keep going...
As for footer that really should just be log-lines from various plugins/engines...

**Comment by jonasfj** [comment]
I'm happy with the current solution, feel free to reopen with more details...
