### ISSUE TITLE
Avoid the need for CGO

### ISSUE THREAD

**Issue by jonasfj** [taskcluster/taskcluster-worker#264]
Building with `CGO_ENABLED=0` is good because:
 * it gives us static binaries
 * easy to deploy in a docker container or VM image

Afaik, the only hold up is `engines/native/system` that needs `os/user` which requires cgo. If we can avoid that we don't need to use cgo, which will make the deployment story easier...

**Comment by jonasfj** [comment]
Adding to this discussion, we have two options for zstd:
 A) [use golang bindings](https://github.com/DataDog/zstd) this will require CGO
 B) call `zstd` as external program

If we do (A) then we should be careful to ensure glibc compatibility when deploying.

If we do (B) then we'll need to ensure `zstd` is installed when deploying.

In both cases it's tempting to solve the problem by throwing `taskcluster-worker` in a docker image..
For docker-engine that'll be somewhat problematic. For qemu-engine, we'll definitely want to do because it allows us to lock the binaries we use, such as: qemu, qemu-img, iptables, dnsmasq, etc.

I might be tempting to do (A) as it allows easier deployment for docker-engine, granted we'll have to ensure glibc compatibility or [link against musl libc](http://dominik.honnef.co/posts/2015/06/statically_compiled_go_programs__always__even_with_cgo__using_musl/) something like `CC=musl-gcc go build --ldflags '-linkmode external -extldflags "-static"'`

**Comment by jonasfj** [comment]
@petemoore, @walac, do any of you two have opinions on this?

I see it as slightly appealing to embed zstd and rely on CGO... and then just link statically with musl in releases where that is desired.

**Comment by walac** [comment]
My opinion is that we shouldn't start to hack the code to solve a problem we don't know we will have. So, stick to CGO until a real-life issue rises.

**Comment by jonasfj** [comment]
@walac, makes a good point...

I somehow confused myself into thinking we had switch from CGO, but our releases are not CGO... at-least not for linux... So I'll just close this.
