### ISSUE TITLE
Add a `version` subcommand

### ISSUE THREAD

**Issue by djmitche** [taskcluster/taskcluster-worker#278]
I just got a log without any logprefix stuff, and I wasn't sure if that was because the worker had been reverted to an older version.  I don't have any good way to identify the version that's installed on-disk, though.  A `taskcluster-worker version` command would be really handy.

**Comment by djmitche** [comment]
I'd defer to @petemoore. For tc-cli, yes, wrap with Make and pass it in as a linker symbol.

**Comment by jonasfj** [comment]
I guess I could just have googled it:
https://www.atatus.com/blog/golang-auto-build-versioning/

This seem like a nice solution... link flags is pretty cool...

**Comment by petemoore** [comment]
Agreed - I'd propose definitely taking git commit sha, and perhaps a semver version number too - but if you only take one, the SHA is awesome, as there is no disputing the source it was built from.

**Comment by petemoore** [comment]
Note I didn't do this in generic-worker, but I think it is a nicer solution. In generic-worker I have a release script which search/replaces version number in source, tags source tree, pushes, etc. It works, but doing via linker and not needing to patch the source seems nicer.
