### ISSUE TITLE
Upgrade to go 1.9

### ISSUE THREAD

**Issue by jonasfj** [taskcluster/taskcluster-worker#325]

**Comment by jonasfj** [comment]
@walac and @petemoore do you guys agree?

**Comment by walac** [comment]
I personally have no strong opinion on this. It is a compiled language, I don't think it will affect production. Is there anything special in 1.9 we want to take advantage of?

**Comment by jonasfj** [comment]
nothing important.. performance and few new functions... maybe some security fixes...

this is more of a let's try to stay up to date thing :)

**Comment by walac** [comment]
I am ok with that then.

**Comment by jonasfj** [comment]
Fixed in #332 (which lands any moment now)

We're skipping directly to golang 1.10, why not...
