### ISSUE TITLE
Include stacks in the report when watchdog fails

### ISSUE THREAD

**Issue by jrmuizel** [taskcluster/taskcluster-worker#327]
In https://bugzilla.mozilla.org/show_bug.cgi?id=1405767 we're running into watchdog failures
It would be nice if we got stack traces when this was happening.

It looks like https://golang.org/pkg/runtime/#Stack can give us this.

**Comment by jonasfj** [comment]
Note: it seems bc as similar issues, I suspect this is a bug / race condition or similar somewhere in the worker code. And I agree that dumping stack traces might be useful.

**Comment by jonasfj** [comment]
Fixed in #327
